### ISSUE TITLE
how to create own 6dpose dataset 

### ISSUE THREAD

**Issue by CaffeMrDe** [meiqua/6DPose#3]
I brower the net http://ptak.felk.cvut.cz/6DB/public/ and saw so many dataset .
They are what I want. I have anothor sort of dataset.

**Comment by meiqua** [comment]
Do you mean labeling your own dataset? A typical method is to record a  sequence of RGBD images, then register them. There is a good [repo](https://github.com/F2Wang/ObjectDatasetTools) to start with.

**Comment by CaffeMrDe** [comment]
Oh, yeah. I see ,thanks you.
