### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by CaffeMrDe** [meiqua/6DPose#4]
`/home/xxxx/testCode/6DPose/linemodLevelup/linemodLevelup.cpp:110:27: error: ‘VoxelDownSample’ is not a member of ‘open3d’
     auto model_pcd_down = open3d::VoxelDownSample(*model_pcd, voxel_size);
                           ^
/home/xxxx/testCode/6DPose/linemodLevelup/linemodLevelup.cpp:111:27: error: ‘VoxelDownSample’ is not a member of ‘open3d’
     auto scene_pcd_down = open3d::VoxelDownSample(*scene_pcd, voxel_size);
                           ^
/home/xxx/testCode/6DPose/linemodLevelup/linemodLevelup.cpp:121:79: error: invalid initialization of reference of type ‘const std::vector<std::shared_ptr<const open3d::geometry::Geometry> >&’ from expression of type ‘<brace-enclosed initializer list>’
        open3d::visualization::DrawGeometries({model_pcd_down, scene_pcd_down});
                                                                              ^
In file included from /usr/local/include/Open3D/Open3D.h:68:0,
                 from /home/xxxxxx/testCode/6DPose/linemodLevelup/linemodLevelup.cpp`

what your open3D version? When I  make  the project , the error occur.
Thanks

**Comment by meiqua** [comment]
Newest verson of course. Is it the lastest repo in your local branch? Open3d used to change its namespace once, and this repo has [adapted](https://github.com/meiqua/6DPose/blob/8bf29d48625fa570432d5f6172941bdecae9fee7/linemodLevelup/linemodLevelup.cpp#L107) to it.

**Comment by CaffeMrDe** [comment]
yes, the local branch is lastest. I read the open3D code . But the code  is new.
About     open3d::geometry::VoxelDownSample. 

Only show the function:
`std::shared_ptr<PointCloud> VoxelDownSample(double voxel_size) const;`

Can you tell me your local open3D version?

**Comment by meiqua** [comment]
0.7.0
Really? but your error report shows that it's different from the lastest. 
```
error: ‘VoxelDownSample’ is not a member of ‘open3d’ auto model_pcd_down = open3d::VoxelDownSample(*model_pcd, voxel_size);
```
The latest has added a nested namespace according to newest open3d.
``` c++
auto model_pcd_down = open3d::geometry::VoxelDownSample(*model_pcd, voxel_size);
```

**Comment by CaffeMrDe** [comment]
Oh yes! I solve the question.I download the open3D  0.7 release version and make again, the project build sucessfully!  Thanks !

**Comment by meiqua** [comment]
Oh, I just noticed that ICP threshold is 0.1 here. [0.01 is better](https://github.com/meiqua/6DPose/blob/eec3a105dd8bedc4449f601b1b879922b5a75497/linemodLevelup/linemodLevelup.cpp#L31) in my test.
